# Generated by Django 6.0.4 on 2026-05-06 15:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название фильма')),
                ('genre', models.CharField(max_length=100, verbose_name='Жанр')),
                ('release_year', models.PositiveIntegerField(verbose_name='Год выпуска')),
                ('status', models.CharField(choices=[('watchlist', 'Хочу посмотреть'), ('watching', 'Смотрю'), ('watched', 'Посмотрел')], default='watchlist', max_length=20, verbose_name='Статус')),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Личная оценка (1-10)')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь-владелец')),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
    ]
