TEMP_NOTES = [
        {
            "id": 1,
            "title": "First steps Django Framework",
            "category": "backend",
            "content": "First steps Django Framework",
            "created_at": "2026-04-09",
            "tags": ["Django", "Framework", "Python"],
        },
        {
            "id": 2,
            "title": "Understanding REST API",

            "content": "Basics of REST architecture and HTTP methods",
            "created_at": "2026-04-09",
            "tags": ["API", "REST", "HTTP"],
        },
        {
            "id": 3,
            "title": "Intro to React",
            "category": "frontend",
            "content": "Components, props and state in React",
            "created_at": "2026-04-09",
            "tags": ["React", "JavaScript", "Frontend"],
        },
        {
            "id": 4,
            "title": "Working with Docker",
            "category": "devops",
            "content": "Containerization basics and docker commands",
            "created_at": "2026-04-09",
            "tags": ["Docker", "DevOps", "Containers"],
        },
        {
            "id": 5,
            "title": "PostgreSQL Basics",
            "category": "database",
            "content": "Creating tables and basic SQL queries",
            "created_at": "2026-04-09",
            "tags": ["SQL", "PostgreSQL", "Database"],
        },
        {
            "id": 6,
            "title": "Authentication with JWT",
            "category": "backend",
            "content": "How JWT works and implementation steps",
            "created_at": "2026-04-09",
            "tags": ["JWT", "Auth", "Security"],
        },
        {
            "id": 7,
            "title": "Deploying to AWS EC2",
            "category": "cloud",
            "content": "Steps to deploy app on EC2 instance",
            "created_at": "2026-04-09",
            "tags": ["AWS", "EC2", "Deployment"],
        },
        {
            "id": 8,
            "title": "CSS Flexbox Guide",
            "category": "frontend",
            "content": "Layout design using flexbox",
            "created_at": "2026-04-09",
            "tags": ["CSS", "Flexbox", "UI"],
        },
        {
            "id": 9,
            "title": "Python Generators",
            "category": "backend",
            "content": "Yield keyword and generator functions",
            "created_at": "2026-04-09",
            "tags": ["Python", "Generators"],
        },
        {
            "id": 10,
            "title": "Git Basics",
            "category": "tools",
            "content": "Version control with git and common commands",
            "created_at": "2026-04-09",
            "tags": ["Git", "Version Control"],
        },
    ]